name: Remove Branch

on:
  workflow_call:
    inputs:
      branch:
        description: 'branch to delete'
        required: true
        type: string
    secrets:
      bingo_token:
        required: true

jobs:
  remove_branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.branch }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BINGO_TOKEN }}
      - run: |
          echo 'branch to be dealt with: ${{ inputs.branch }} '
          sed -i '/${{ inputs.branch }},/d' bingo.csv
          git config --global user.name "some-bot"
          git config --global user.email "some-bot@users.noreply.github.com"
          git add bingo.csv
          git commit -m "removed ${{ inputs.branch }} on behalf of tbd"
          git push